name             'bind'
maintainer       'Vegard Hansen'
maintainer_email 'vegard.x@gmail.com'
license          'GNU Public License 2.0'
description      'Installs/Configures bind'
long_description 'Installs/Configures bind'
version          '0.1.0'

supports 'debian'
depends 'chef-sugar'
